export const colors = {
  primary: '#000412',
  primaryContainer: '#0F1E36',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#7886A3',
  secondary: '#3755C3',
  secondaryContainer: '#708CFD',
  secondaryFixed: '#DDE1FF',
  background: '#F8F9FF',
  surface: '#FFFFFF',
  surfaceDim: '#CBDBF5',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#EFF4FF',
  surfaceContainer: '#E5EEFF',
  surfaceContainerHigh: '#DCE9FF',
  surfaceContainerHighest: '#D3E4FE',
  inverseSurface: '#213145',
  inverseOnSurface: '#EAF1FF',
  outline: '#75777E',
  outlineVariant: '#C5C6CE',
  border: '#E5EEFF',
  text: '#0B1C30',
  textMuted: '#44474D',
  success: '#00875A',
  successBg: '#E3FCEF',
  warning: '#D97706',
  warningBg: '#FFFBEB',
  error: '#BA1A1A',
  errorBg: '#FFDAD6',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#93000A',
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
};

export const radius = {
  sm: 6,
  md: 10,
  lg: 14,
  xl: 20,
  full: 999,
};
